name: selenium

# Controls when the action will run. 
on:
  
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.6
      - name: 'Install requirements'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
        
      - name: Prepare chromedriver
        uses: nanasess/setup-chromedriver@v1
        
      - name: 'Working'
        run: |
          # sudo cp -p ./chromedriver /usr/bin/
          # chmod -R 777 /usr/bin/chromedriver
          # python ./gamekegs.py ${{ secrets.GAMEKEGS_USERNAME }} ${{ secrets.GAMEKEGS_PASSWORD }}

